// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXPjTsboqzfEGq1UCx0KwmeAPb-AhXVzg',
    appId: '1:1086210396463:web:d19e15f6e71119777a91da',
    messagingSenderId: '1086210396463',
    projectId: 'chat-app-dde65',
    authDomain: 'chat-app-dde65.firebaseapp.com',
    storageBucket: 'chat-app-dde65.appspot.com',
    measurementId: 'G-J0EBCS2CSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjVp3ORTODv5-So8JcKSMMU9RbCEk4GdY',
    appId: '1:1086210396463:android:0e15adb29bb99fa27a91da',
    messagingSenderId: '1086210396463',
    projectId: 'chat-app-dde65',
    storageBucket: 'chat-app-dde65.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuDPigawI8fmnLOtpaNar8w9v4ybhGSE4',
    appId: '1:1086210396463:ios:a94f0a01eaf6bae77a91da',
    messagingSenderId: '1086210396463',
    projectId: 'chat-app-dde65',
    storageBucket: 'chat-app-dde65.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuDPigawI8fmnLOtpaNar8w9v4ybhGSE4',
    appId: '1:1086210396463:ios:f56f3c3892aa88dd7a91da',
    messagingSenderId: '1086210396463',
    projectId: 'chat-app-dde65',
    storageBucket: 'chat-app-dde65.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
